pub fn help_text() -> String {
    [
        "/new - start a fresh model session",
        "/sessions - list resumable sessions",
        "/resume <session_id> - resume a saved session",
        "/delete <session_id> - delete a saved session",
        "/providers - list configured provider profiles",
        "/provider <profile_id> - switch provider profile",
        "/provider-remove <profile_id> - remove a provider profile",
        "/model <model_id> - change the active profile model",
        "/ping - check daemon",
        "/status - compact operator status",
        "/doctor - inspect local runtime health",
        "/agents - list registered agents",
        "/tools - list governed tools and policies",
        "/enable <tool_id> - enable a governed tool",
        "/disable <tool_id> - disable a governed tool",
        "/skills - list skill packs and tool bindings",
        "/skill-install <bundle.json> - install a self-signed skill bundle",
        "/mcp - list MCP adapters",
        "/mcp-add <id> <name> <command> [args...] - register an MCP adapter",
        "/mcp-start <id> - start and discover MCP tools",
        "/mcp-stop <id> - stop an MCP adapter",
        "/mcp-remove <id> - remove an MCP adapter",
        "/invoke <tool_id> [--approve] [key=value ...] - invoke governed tool",
        "/tool-history - show recent tool invocation audit",
        "/maintenance - show retention policy",
        "/prune - run retention now",
        "/graph [label] - explore the knowledge graph as text",
        "/security - list the process.exec command allowlist",
        "/allow <program> - allow a program for process.exec",
        "/disallow <program> - remove a program from the allowlist",
        "/workflows - list workflows",
        "/workflow <title> - start workflow and stop at approval",
        "/watch <workflow_id> - watch workflow progress",
        "/inspect <workflow_id> - show workflow status and recent events",
        "/logs <workflow_id> <agent_id> - show agent logs",
        "/approve <workflow_id> - approve with hybrid mode",
        "/cancel <workflow_id> - cancel workflow",
        "/memory - show memory commands",
        "/remember <text> - store long-term memory",
        "/lesson <scope> | <error> | <correction> - store negative lesson",
        "/recall [query] - recall memory",
        "/dreams [query] - recall nightly dreams",
        "/task <text> - store an explicit task",
        "/clear - clear transcript",
        "plain text - stream a model response with governed tools",
        "Up/Down - command history",
        "Left/Right/Home/End/Delete - edit prompt",
        "PageUp/PageDown - scroll transcript",
        "Ctrl-L - clear transcript",
        "Ctrl-U - clear prompt",
        "Esc or Ctrl-C - cancel active request, otherwise exit",
    ]
    .join("\n")
}

pub fn memory_help_text() -> String {
    [
        "memory commands",
        "/remember <text>",
        "/lesson <scope> | <error> | <correction>",
        "/recall [query]",
        "/dreams [query]",
    ]
    .join("\n")
}
